<%@ Page  Language="C#" MasterPageFile="~/MasterPage2.master" AutoEventWireup="true" 
CodeFile="okRegister.aspx.cs" Inherits="okRegister"  %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">


<!-- Google Code for &#1500;&#1488;&#1495;&#1512; &#1492;&#1512;&#1513;&#1502;&#1492; Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 989445501;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "mBqzCOvsvw0Q_frm1wM";
var google_conversion_value = 0;
/* ]]> */


  $(document).ready(function () {
var name= '<%= IfNameUser  %>';
var email= '<%= IfMailUser  %>';
  $( "input[name$='fields[subscribers_email]']" ).val(email);
   $( "input[name$='fields[subscribers_name]']" ).val(name);
  // $("#f").submit();
   
 });
</script>
<!-- Generated by responder.co.il -->
<script type="text/javascript">
<!--
    function responder_validation(form) {
        var inputs = form.getElementsByTagName('input');
        var selects = form.getElementsByTagName('select');
        var filter_email = /^([\w\!\#$\%\&\'\*\+\-\/\=\?\^\`{\|\}\~]+\.)*[\w\!\#$\%\&\'\*\+\-\/\=\?\^\`{\|\}\~]+@((((([a-z0-9]{1}[a-z0-9\-]{0,62}[a-z0-9]{1})|[a-z])\.)+[a-z]{2,6})|(\d{1,3}\.){3}\d{1,3}(\:\d{1,5})?)$/i;
        var filter_phone = /^(?:|(?:050|052|053|054|055|057|058|02|03|04|08|09)\d{7,7})$/;
var a;
        for (a = 0; a < inputs.length; a++) {
            switch (inputs[a].name) {
                case 'fields[subscribers_email]':
                    if (!filter_email.test(inputs[a].value)) {
                     
                       a=1;
                        inputs[a].focus();
                        return false;
                    }

                    break;
                case 'fields[subscribers_phone]':
                    var phone = inputs[a].value.replace(/-|\s/g, '');
                    if (!filter_phone.test(phone.length == 0 || phone.charAt(0) == '0' ? phone : '0' + phone)) {
                        //alert('מספר הטלפון הנייד אינו חוקי');
						a=1;
                        inputs[a].focus();
                        return false;
                    }

                    break;
                case 'fields[subscribers_name]':
                    if (inputs[a].value.replace(/^\s+|\s+$/g, '') == '') {
                       
                       a=1;
                        inputs[a].focus();
                        return false;
                    }

                    break;
            }
        }

        for (a = 0; a < selects.length; a++) {
            switch (selects[a].name) {
            }
        }

        if (document.charset)
            form.encoding.value = document.charset;
        else if (document.defaultCharset)
            form.encoding.value = document.defaultCharset;
        else if (document.characterSet)
            form.encoding.value = document.characterSet;

        return true;
    }
//-->
</script>

<form id="f" method="post" action="https://cp.responder.co.il/subscribe.php" onsubmit="return responder_validation(this);" style="display:none">
<table border="0" dir="rtl">
	<tbody>
		<tr>
			<td><b><%=Resources.Resource.email_%></b> <span style="color:red;">*</span></td>
			<td><input type="text" name="fields[subscribers_email]" size="14" dir="ltr" /></td>
		</tr>
		<tr>
			<td><b><%=Resources.Resource.name%></b> <span style="color:red;">*</span></td>
			<td><input type="text" name="fields[subscribers_name]" size="14" dir="rtl" /></td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="hidden" name="form_id" value="56435" />
				<input type="hidden" name="encoding" value="" />
				<input type="submit" value="<%=Resources.Resource.register_%>" id="submitbtn"/>
			</td>
		</tr>
	</tbody>
</table>
</form>

<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/989445501/?value=0&amp;label=mBqzCOvsvw0Q_frm1wM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


    <!-- Facebook Conversion    -->                                    
<script type="text/javascript">
var fb_param = {};
fb_param.pixel_id = '6009077544232';
fb_param.value = '0.00';
(function(){
  var fpw = document.createElement('script');
  fpw.async = true;
  fpw.src = '//connect.facebook.net/en_US/fp.js';
  var ref = document.getElementsByTagName('script')[0];
  ref.parentNode.insertBefore(fpw, ref);
})();
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6009077544232&amp;value=0" /></noscript>
<!---END FACEBOOK-->
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
	<table align="center"  style="border:none;height:500px" width="80%" >
      <tr>
			<td align="center">
			<h1><label><%=Resources.Resource.your_registration_received%></label></h1>
				<h5><label><%=Resources.Resource.activate_the_account%></label></h5>
			</td>
		</tr>
		</table>
</asp:Content>

